apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-app
  labels:
    app: test-app
  name: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - image: ghcr.io/yuta15/gitops-practice:1b8ba018c972b1dcf8bac61be2563e75be5abf4a
          name: test-app
