apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-app
  labels:
    app: test-app
  name: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - image: ghcr.io/yuta15/gitops-practice:16069377f4a4da8de1fec0413f8091505b6159de
          name: test-app
