apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-app
  labels:
    app: test-app
  name: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - image: ghcr.io/yuta15/gitops-practice:830d49b4813bb4e3a5fa0981ebf3a97d6e01a70b
          name: test-app
