resources:
  - ../

namespace: test-app-dev

nameSuffix: -dev

labels:
  - pairs: 
      environment: dev

images: 
  - name: ghcr.io/yuta15/gitops-practice
    newTag: 16069377f4a4da8de1fec0413f8091505b6159de