resources:
  - ../base/

namespace: test-app-dev

nameSuffix: -dev

labels:
  - pairs: 
      environment: dev

images: 
  - name: ghcr.io/yuta15/gitops-practice
    newTag: 2fb17254999d3ec93d58afefc512b386a5804d60