resources:
  - ../base/

namespace: test-app-prd

nameSuffix: -prd

labels:
  - pairs: 
      environment: prd

images: 
  - name: ghcr.io/yuta15/gitops-practice
    newTag: 16069377f4a4da8de1fec0413f8091505b6159de